# Generated by Django 3.1.3 on 2021-01-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210106_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
